// src/modules/base/components/BaseHeader.tsx
import { NavLink } from 'react-router-dom';
export default function BaseHeader() {
	return (
		<div className="border-b p-2 bg-light sticky top-0 z-50">
			<div className="max-w-7xl mx-auto py-2 flex justify-between items-center">
				<NavLink to="/" className="flex items-center gap-2">
					{/* <FontAwesomeIcon icon={faBars} size="2x" /> */}
					<img src="https://learningafrica.com/assets/images/logos/logo.png" alt=""  className='h-14 w-fit ' />
					{/* <h2 className="text-xl uppercase font-bold">Learning africa</h2> */}
				</NavLink>
				<div>
					<ul className="flex gap-4 uppercase">
						<li className="inline-block mr-2">
							<NavLink to="/" className="text-sm  font-bold">
								Home
							</NavLink>
						</li>
						<li className="inline-block mr-2">
							<NavLink to="/about" className="text-sm  font-bold">
								About
							</NavLink>
						</li>
						<li className="inline-block mr-2">
							<NavLink
								to="/contact"
								className="text-sm  font-bold"
							>
								Contact
							</NavLink>
						</li>
						<li className="inline-block mr-2">
							<NavLink to="/login" className="text-sm  font-bold">
								Login
							</NavLink>
						</li>
					</ul>
				</div>
				<div>
					<ul>
						<li className="inline-block mr-2">
							<NavLink
								to="/login"
								className="text-sm uppercase font-bold bg-orange-500 text-white px-4 py-2 rounded"
							>
								Become an Instructor
							</NavLink>
						</li>{' '}
						<li className="inline-block mr-2">
							{/* <label htmlFor="">
									Lang
								</label> */}
							<select name="" id="">
								<option value="">English</option>
								<option value="">Spanish</option>
								<option value="">French</option>
							</select>
						</li>
					</ul>
				</div>
			</div>
		</div>
	);
}

// components/base/base-header.vue
<script setup lang="ts">


// const isScroll = ref(false);
// const isAuthenticated = ref(false);


</script>
<template>
    <div class="border-b w-full sticky top-0 flex flex-col gap-0 p-4 bg-white z-50">
        <max-width-wrapper class-name="flex justify-between items-center">
            <div class="flex items-center gap-2">

                <img src="https://avatars.githubusercontent.com/u/150797856?s=200&v=4" alt=""
                    class="h-12 w-12 rounded-full">
                <span class="text-xl hidden md:block  text-primary-pk ml-4 font-bold uppercase">
                    Learning Africa
                </span>
            </div>
            <div>
                <nuxt-link to='/login' class="text-sm font-medium text-gray-900 ml-4 border px-4 py-2 rounded">
                    Sign in
                </nuxt-link> <nuxt-link to='/register' class="text-sm font-medium text-white ml-4 px-4 py-2 bg-black rounded">
                    Sign up
                </nuxt-link>
            </div>

        </max-width-wrapper>
    </div>
</template>

<style scoped>
/**
  <div
        class="w-full transition-all duration-500 py-2  bg-primary-pk bg-blend-overlay bg-opacity-10">
        <max-width-wrapper class-name="flex justify-between items-center">
            <div class="w-full flex justify-between items-center p-4 rounded-md h-20">

                <div className="w-full flex items-center">
                    <div className="flex items-center">
                        <img className="w-14 h-14 rounded-full"
                            src="https://avatars.githubusercontent.com/u/150797856?s=200&v=4" alt="avatar" />
                        <div class="text-xl hidden md:block  text-primary-pk ml-4 font-bold uppercase">
                            Learning Africa
                        </div>
                    </div>
                </div>
                <div>
                    <div className="items-center hidden md:flex">
                        <div className="text-sm font-medium text-gray-900">
                            Home
                        </div>
                        <div className="text-sm font-medium text-gray-900 ml-4">
                            About
                        </div>
                        <div className="text-sm font-medium text-gray-900 ml-4">
                            Contact
                        </div>
                    </div>
                </div>
                <div className="flex items-center">
                    <div v-if="isAuthenticated">
                        <div className="flex items-center gap-2">
                            <div className="text-sm font-medium text-gray-900 ml-4">
                                <nuxt-link to='/' class="text-sm font-medium text-gray-900 ml-4"
                                    :class="{ 'bg-primary-pk px-4 text-white py-2 rounded': isScroll }">
                                    Dashboard
                                </nuxt-link>
                            </div>
                            <img className="w-8 h-8 rounded-full"
                                src="https://secure.gravatar.com/avatar/2b7b7c9b5c9c5b5c9b7c9b5c9b7c9b5c?s=200&d=mm&r=g"
                                alt="avatar" />
                        </div>
                    </div>
                    <div v-else className="flex items-center" class="flex items-center">
                        <nuxt-link to='' class="text-sm font-medium text-blue-600 hover:underline ml-4">
                            Login
                        </nuxt-link>
                        <div
                            className="text-sm font-medium text-gray-900 ml-4 bg-primary-pk px-4 md:px-8 py-2 md:py-4 rounded">
                            Sign up
                        </div>
                    </div>
                </div>
            </div>
        </max-width-wrapper>
    </div> */
</style>
