// src/client/accounts/Register.tsx
import { NavLink } from 'react-router-dom';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Toaster, toast } from 'react-hot-toast';

import {
	Form,
	FormControl,
	// FormDescription,
	FormField,
	FormItem,
	FormLabel,
	FormMessage
} from '@/components/ui/form';
import { zodResolver } from '@hookform/resolvers/zod';
import * as z from 'zod';
import { AuthApiService } from '@/lib/services/api-services/auth.service';
import { useForm, SubmitHandler } from 'react-hook-form';
import { useMutation } from '@tanstack/react-query';
import { cn } from '@/lib/utils';

const authApi = new AuthApiService();
const RegisterSchema = z
	.object({
		email: z.string().email('Please enter a valid email'),
		first_name: z.string({ required_error: 'First name is required' }),
		username: z.string({ required_error: 'Username is required' }),
		is_admin: z.boolean().default(true), //admin@learningafrica.com
		is_instructor: z.boolean().default(false), //instructor@learningafrica.com
		is_student: z.boolean().default(false), // student@learningafrica.com
		is_super_admin: z.boolean().default(false), // superadmin@learningafrica
		last_name: z.string({ required_error: 'Last name is required' }),
		password: z
			.string({})
			.min(8, { message: 'Password must be at least 8 characters long' })
			.max(20, {
				message: 'Password must be at most 50 characters long'
			}),
		confirm_password: z.string()
	})
	.refine((data) => data.password === data.confirm_password, {
		message: 'Passwords do not match',
		path: ['confirm_password']
	});

export type RegisterFormType = z.infer<typeof RegisterSchema>;

export default function Register() {
	const form = useForm<RegisterFormType>({
		resolver: zodResolver(RegisterSchema),
		defaultValues: {
			is_student: false,
			confirm_password: '',
			password: '',
			email: '',
			first_name: '',
			is_admin: true,
			is_instructor: false,
			is_super_admin: false,
			last_name: '',
			username: ''
		}
	});
	// const queryClient = useQueryClient();
	const mutation = useMutation({
		mutationFn: authApi.register,
		onSuccess: () => {
			toast.success('Registration successful', {
				className: 'bg-green-500 text-white font-bold p-4 rounded-md',
				icon: '👏',
				position: 'top-right',
				duration: 5000
			});
		},
		onError: (error) => {
			console.log(error);
			toast.error('Registration failed', {
				className: 'bg-red-500 text-white font-bold p-4 rounded-md',
				icon: '👏',
				position: 'top-right',
				duration: 5000
			});
		}
	});
	const onSubmit: SubmitHandler<RegisterFormType> = async (values) => {
		// console.log(values);
		// toast.success('Registration successful', {
		// 	className: 'bg-green-500 text-white font-bold p-4 rounded-md',
		// 	icon: '👏',
		// 	position: 'top-right',
		// 	duration: 5000
		// });
		mutation.mutate(values);
		// const res = await api.register(values);
		// console.log(res);
	};
	return (
		<div className="bg-light p-4">
			<Toaster />
			<div className="max-w-7xl mx-auto py-4 flex flex-col items-center justify-center min-h-[70vh]">
				<div>
					{/* Create account title */}
					<h1 className="text-4xl font-bold">Register</h1>
				</div>
				<Form {...form}>
					<form
						action=""
						className={cn(
							'flex flex-col gap-4 w-full max-w-2xl mx-auto p-4'
						)}
						onSubmit={form.handleSubmit(onSubmit)}
					>
						<div
							className={cn(
								'grid grid-cols-1 md:grid-cols-2 gap-4'
							)}
						>
							{/* First name */}
							<FormField
								control={form.control}
								name="first_name"
								render={({ field }) => (
									<FormItem className={cn('w-full')}>
										<FormLabel>First name</FormLabel>
										<FormControl>
											<Input
												placeholder="First name"
												className={cn('w-full')}
												{...field}
											/>
										</FormControl>
										{/* <FormDescription>
										This is your public display name.
									</FormDescription> */}
										<FormMessage />
									</FormItem>
								)}
							/>
							{/* Last name */}
							<FormField
								control={form.control}
								name="last_name"
								render={({ field }) => (
									<FormItem>
										<FormLabel>Last Name</FormLabel>
										<FormControl>
											<Input
												placeholder="Last name"
												{...field}
											/>
										</FormControl>
										{/* <FormDescription>
										This is your public display name.
									</FormDescription> */}
										<FormMessage />
									</FormItem>
								)}
							/>
							{/* Last name */}
							<FormField
								control={form.control}
								name="username"
								render={({ field }) => (
									<FormItem>
										<FormLabel>Username</FormLabel>
										<FormControl>
											<Input
												placeholder="Username"
												{...field}
											/>
										</FormControl>
										{/* <FormDescription>
										This is your public display name.
									</FormDescription> */}
										<FormMessage />
									</FormItem>
								)}
							/>
							{/* Email */}
							<FormField
								control={form.control}
								name="email"
								render={({ field }) => (
									<FormItem>
										<FormLabel>Email</FormLabel>
										<FormControl>
											<Input
												placeholder="example@email.com"
												{...field}
											/>
										</FormControl>
										{/* <FormDescription>
										This is your public display name.
									</FormDescription> */}
										<FormMessage />
									</FormItem>
								)}
							/>
						</div>
						{/* Password */}
						<FormField
							control={form.control}
							name="password"
							render={({ field }) => (
								<FormItem>
									<FormLabel>Password</FormLabel>
									<FormControl>
										<Input
											placeholder="********"
											type="password"
											{...field}
										/>
									</FormControl>
									{/* <FormDescription>
										This is your public display name.
									</FormDescription> */}
									<FormMessage />
								</FormItem>
							)}
						/>
						{/* Confirm Password */}
						<FormField
							control={form.control}
							name="confirm_password"
							render={({ field }) => (
								<FormItem>
									<FormLabel>Password</FormLabel>
									<FormControl>
										<Input
											placeholder="********"
											type="password"
											{...field}
										/>
									</FormControl>
									{/* <FormDescription>
										This is your public display name.
									</FormDescription> */}
									<FormMessage />
								</FormItem>
							)}
						/>
						<Button
							type="submit"
							className={
								cn(
									'bg-primary text-white font-bold py-4 px-8 rounded-md',{
										'opacity-50': mutation.isPending,
										'cursor-not-allowed': mutation.isPending
									}
								)
							}
							disabled={mutation.isPending}
						>
							{mutation.isPending ? 'Loading...' : 'Register'}
						</Button>
						{/* Login link */}
						<div className="flex-1">
							<p>
								Already have an account?{' '}
								<NavLink to="/login" className="text-blue-500">
									Login
								</NavLink>
							</p>
						</div>
					</form>
				</Form>
			</div>
		</div>
	);
}

// pages/register.vue
<script setup lang="ts">
import { useVuelidate } from "@vuelidate/core";
import { minLength, required, email, helpers } from "@vuelidate/validators";
definePageMeta({
	middleware: ["open-auth"]
	// or middleware: 'auth'
});
type RegisterForm = {
	first_name: string;
	last_name: string;
	username: string;
	email: string;
	password: string;
	confirm_password: string;
	is_student: boolean;
	is_instructor: boolean;
};
const { $openAxios, $notify } = useNuxtApp();
const form = ref<RegisterForm>({
	first_name: "",
	last_name: "",
	username: "",
	email: "",
	password: "",
	confirm_password: "",
	is_student: false,
	is_instructor: true,
});
const rules = {
	first_name: {
		required: helpers.withMessage("First name is required", required),
	},
	last_name: {
		required: helpers.withMessage("Last name is required", required),
	},
	username: {
		required: helpers.withMessage("Username is required", required),
	},
	email: {
		required: helpers.withMessage("Email is required", required),
		email: helpers.withMessage("Email must be valid", email),
	},
	password: {
		required: helpers.withMessage("Password is required", required),
		minLength: helpers.withMessage(
			"Password must be at least 6 characters",
			minLength(6)
		),
		// minLength(6, "Password must be at least 6 characters"),
	},
	confirm_password: {
		required: helpers.withMessage("Confirm password is required", required),
		sameAsPassword: helpers.withMessage("Passwords do not match", sameAsPassword),
	},
};

function sameAsPassword(value: string,) {
	return form.value.password === value;
}
const auth = useAuthStore();
const $v = useVuelidate(rules, form);
const showPassword = ref(false);
const insLoading = ref(false);
const router = useRouter();
const handleSubmit = async () => {
	// alert("Something good");
	console.log("submitting");
	$v.value.$validate();
	// $v.$touch();
	if ($v.value.$error) {
		return;
	}
	insLoading.value = true;
	try {
		const response = await $openAxios.post("/auth/register/", form.value);
		if (response.status === 200 || response.status === 201) {
			await $notify.fire({
				title: "Success",
				icon: "success",
				confirmButtonText: "Close",
				text: "Registration successful"
			});
			await router.push("/login");
		} else {
			console.log(response.data);

		}
		// eslint-disable-next-line @typescript-eslint/no-explicit-any
	} catch (error: any) {
		console.error({ error });
		if (error.response.data.detail) {
			$notify.fire({
				title: "Error",
				icon: "error",
				confirmButtonText: "Close",
				text: error.response.data.detail
			});
		}
	} finally {
		insLoading.value = false;
	}
};
</script>

<template>

	<div class="bg-gray-100 p-4 md:p-10 min-h-[100vh] flex justify-center items-center">
		<max-width-wrapper class-name="flex items-center justify-center">
			<form @submit.prevent.stop="handleSubmit"
				class="min-h-[50vh] w-full max-w-xl bg-white p-4 md:p-10 rounded-lg shadow-md gap-5 flex flex-col justify-center items-center">
				<div>
					<div class="flex items-center justify-center">
						<img src="https://avatars.githubusercontent.com/u/150797856?s=200&v=4" alt=""
							class="h-20 w-20 object-cover rounded-full border border-primary" />
					</div>
					<h1 class="text-center">
						<nuxt-link href="/" class="text-2xl font-bold text-primary uppercase tracking-wider">Learning
							Africa</nuxt-link>
					</h1>
				</div>
				<div class="grid sm:grid-cols-2 gap-4">
					<!-- First and last name -->
					<div>
						<label for="first_name">First Name</label>
						<input type="text" id="first_name" name="first_name" placeholder="First name"
							v-model="form.first_name" />
						<div v-if="$v.first_name.$error" class="text-red-500">
							<p v-for="error of $v.first_name.$errors" :key="error.$uid">
								{{ error.$message }}
							</p>
						</div>
					</div>
					<div>
						<label for="last_name">Last Name</label>
						<input type="text" id="last_name" placeholder="Last name" name="last_name"
							v-model="form.last_name" />
						<div v-if="$v.last_name.$error" class="text-red-500">
							<p v-for="error of $v.last_name.$errors" :key="error.$uid">
								{{ error.$message }}
							</p>
						</div>
					</div>
				</div>
				<div class="grid sm:grid-cols-2 gap-4">
					<!-- Username and email -->
					<div>
						<label for="username">Username</label>
						<input type="text" id="username" name="username" placeholder="Username"
							v-model="form.username" />
						<div v-if="$v.username.$error" class="text-red-500">
							<p v-for="error of $v.username.$errors" :key="error.$uid">
								{{ error.$message }}
							</p>
						</div>
					</div>
					<div>
						<label for="email">Email</label>
						<input type="email" id="email" name="email" placeholder="example@gmail.com"
							v-model="form.email" />
						<div v-if="$v.email.$error" class="text-red-500">
							<p v-for="error of $v.email.$errors" :key="error.$uid">
								{{ error.$message }}
							</p>
						</div>
					</div>
				</div>
				<!-- Password -->
				<div>
					<label for="password">Password</label>
					<input :type="showPassword ? 'text' : 'password'" id="password" name="password"
						placeholder="*********" v-model="form.password" />
					<div v-if="$v.password.$error" class="text-red-500">
						<p v-for="error of $v.password.$errors" :key="error.$uid">
							{{ error.$message }}
						</p>
					</div>
				</div>
				<!-- Confirm password -->
				<div>
					<label for="confirm_password">Confirm Password</label>
					<input :type="showPassword ? 'text' : 'password'" id="confirm_password" name="confirm_password"
						placeholder="*******" v-model="form.confirm_password" />
					<div v-if="$v.confirm_password.$error" class="text-red-500">
						<p v-for="error of $v.confirm_password.$errors" :key="error.$uid">
							{{ error.$message }}
						</p>
					</div>
				</div>
				<!-- Show password -->
				<div class="flex items-center gap-2 show-passsword-wrapper">
					<input type="checkbox" id="show_password" name="show_password" v-model="showPassword" />
					<label for="show_password">Show password</label>
				</div>
				<div class="flex flex-col gap-2 w-full md:w-96">
					<button type="submit"
						:class="insLoading ? 'bg-gray-500 cursor-not-allowed' : 'bg-primary text-white p-2 rounded-md w-full hover:bg-primary-dark transition duration-300 ease-in-out'"
						class="bg-primary text-white p-2 rounded-md w-full hover:bg-primary-dark transition duration-300 ease-in-out">
						{{ insLoading ? "Loading..." : "Register" }}
					</button>
				</div>
				<p>
					Already have an account?
					<nuxt-link href="/login"
						class="text-blue-500 hover:underline transition duration-300 ease-in-out">Login</nuxt-link>
				</p>
			</form>
		</max-width-wrapper>
	</div>

</template>

<style scoped>
input {
	@apply border border-gray-300 rounded-md p-2 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent w-full;
}

label {
	@apply text-gray-600 uppercase text-sm;
}

form div {
	@apply w-full;
}

.show-passsword-wrapper {
	@apply w-full;
}

.show-passsword-wrapper input {
	@apply border border-gray-300 rounded-md p-2 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent h-5 w-5;
}
</style>
