// pages/login.vue
<script lang="ts" setup>
import { useVuelidate } from "@vuelidate/core";
import {
	minLength, required, helpers
} from "@vuelidate/validators";

definePageMeta({
	middleware: ["open-auth"],
});
const { $openAxios, $notify } = useNuxtApp();
type LoginUserType = {
	username_or_email: string
	password: string
}

const form = ref<LoginUserType>({
	username_or_email: "",
	password: "",
});

const rules = {
	username_or_email: {
		required: helpers.withMessage("Username or email is required", required),

	},
	password: {
		required: required,
		minLength: helpers.withMessage("Password must be at least 6 characters", minLength(6)),
	},
};
const showPassword = ref(false);
const $v = useVuelidate(rules, form);
const auth = useAuthStore();
const isLoading = ref(false);
const router = useRouter();
const handleSubmit = async () => {
	console.log("submitting");

	$v.value.$validate();
	if ($v.value.$error) {
		return;
	}

	isLoading.value = true;
	try {
		const response = await $openAxios.post("/auth/login/", form.value);
		if (response.status === 200 || response.status === 201) {
			console.log(response.data);
			auth.login({
				access_token: response.data.access_token,
				refresh_token: response.data.refresh_token,
				username: response.data.username,
				user_role: response.data.user_role,
			});
			await $notify.fire({
				title: "Success",
				icon: "success",
				confirmButtonText: "Close",
				text: "Login successful"
			});
			await router.push(auth.dashboardUrl ?? "/");
		} else {
			console.log(response.data);

		}
		// eslint-disable-next-line @typescript-eslint/no-explicit-any
	} catch (error: any) {
		console.error({ error });
		if (error.response.data.detail) {
			$notify.fire({
				title: "Error",
				icon: "error",
				confirmButtonText: "Close",
				text: error.response.data.detail
			});
		}
	} finally {
		isLoading.value = false;
	}
};
</script>

<template>
	<div class="bg-gray-100 p-4 md:p-10 min-h-[100vh] flex justify-center items-center">
		<max-width-wrapper class-name="flex items-center justify-center">
			<form action="" @submit.prevent.stop="handleSubmit"
				class="min-h-[50vh] w-full max-w-xl bg-white p-4 md:p-10 rounded-lg shadow-md gap-5 flex flex-col justify-center items-center">
				<div>
					<div class="flex items-center justify-center">
						<img src="https://avatars.githubusercontent.com/u/150797856?s=200&v=4" alt=""
							class="h-20 w-20 object-cover rounded-full border border-primary">
					</div>
					<h1 class="text-center">
						<nuxt-link href="/" class="text-2xl font-bold text-primary uppercase tracking-wider">Learning
							Africa</nuxt-link>
					</h1>
				</div>
				<div class="flex flex-col gap-2 w-full md:w-96">
					<label for="username_or_email">Email/username</label>
					<input type="text" id="email" name="username_or_email" placeholder="username/email"
						v-model="form.username_or_email" />
					<div v-if="$v.username_or_email.$error" class="text-red-500">
						<p v-for="error of $v.username_or_email.$errors" :key="error.$uid">
							{{ error.$message }}
						</p>
					</div>
				</div>

				<div class="flex flex-col gap-2 w-full md:w-96">
					<label for="password">Password</label>
					<input :type="showPassword ? 'text' : 'password'" id="password" name="password"
						placeholder="********" v-model="form.password" />
					<div v-if="$v.password.$error" class="text-red-500">
						<p v-for="error of $v.password.$errors" :key="error.$uid">
							{{ error.$message }}
						</p>
					</div>
				</div>
				<!-- Show password -->
				<div class="flex w-full md:w-96 items-center gap-2 show-passsword-wrapper">
					<input type="checkbox" id="show_password" name="show_password" v-model="showPassword" />
					<label for="show_password">Show password</label>
				</div>
				<div class="flex flex-col gap-2 w-full md:w-96">
					<button type="submit"
						:class="isLoading ? 'bg-gray-300 cursor-not-allowed' : 'bg-primary text-white p-2 rounded-md w-full hover:bg-primary-dark transition duration-300 ease-in-out'"
						class="bg-primary text-white p-2 rounded-md w-full hover:bg-primary-dark transition duration-300 ease-in-out">
						{{ isLoading ? "Loading..." : "Login" }}
					</button>
				</div>
				<p>
					Don't have an account? <nuxt-link href="/register"
						class="text-blue-500 hover:underline transition duration-300 ease-in-out">Register</nuxt-link>
				</p>
			</form>
		</max-width-wrapper>
	</div>
</template>

<style scoped>
input {
	@apply border border-gray-300 rounded-md p-2 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent w-full;
}

label {
	@apply text-gray-600 uppercase text-sm;
}

.show-passsword-wrapper {
	/* @apply w-full; */
}

.show-passsword-wrapper input {
	@apply border border-gray-300 rounded-md p-2 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent h-5 w-5;
}
</style>

// src/app/(base-app)/auth/login/page.tsx
/* eslint-disable react/no-unescaped-entities */
"use client";
import { useAtom } from "jotai";
import toast, { Toaster } from "react-hot-toast";
import React from "react";
import { useForm, SubmitHandler } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import * as z from "zod";
import { authStoreAtom } from "@/store/auth-atom";
import { Button } from "@/components/ui/button";
import { AxiosError } from "axios";
import {
  FormField,
  FormItem,
  FormLabel,
  FormControl,
  FormMessage,
  Form,
} from "@/components/ui/form";
import { cn } from "@/lib/utils";
import { Input } from "@/components/ui/input";
import Link from "next/link";
import { useMutation, useQueryClient } from "@tanstack/react-query";
import { AuthApiService } from "../_services/auth";
const loginUserSchema = z.object({
  username_or_email: z.string(),
  password: z
    .string({})
    .min(8, { message: "Password must be at least 8 characters long" })
    .max(20, {
      message: "Password must be at most 50 characters long",
    }),
});

export type LoginUserType = z.infer<typeof loginUserSchema>;

function LoginPage() {
  const form = useForm<LoginUserType>({
    resolver: zodResolver(loginUserSchema),
    defaultValues: {
      password: "",
      username_or_email: "",
    },
  });
  const authApi = new AuthApiService();
  const [, setAuth] = useAtom(authStoreAtom);
  const queryClient = useQueryClient();
  const mutation = useMutation({
    mutationFn: authApi.login,
    onSuccess: (data) => {
      toast.success("Login successful", {
        className: "bg-green-500 text-white font-bold p-4 rounded-md",
        icon: "👏👏",
        position: "top-right",
        duration: 5000,
      });

      setAuth({
        access_token: data.access_token,
        refresh_token: data.refresh_token,
        user: {
          username: data.username,
          user_role: data.user_role,
        },
      });
    },
    onError: (error) => {
      if (error instanceof AxiosError) {
        toast.error(error.response?.data.detail, {
          className: "bg-red-500 text-white font-bold p-4 rounded-md",
          icon: "👏",
          position: "top-right",
          duration: 5000,
        });
      }
    },
  });
  const [isPending, setIsPending] = React.useState(false);
  const onSubmit: SubmitHandler<LoginUserType> = async (values) => {
    mutation.mutate(values);
    const res = await authApi.login(values);
  };
  return (
    <div className="bg-light p-4">
      <Toaster />
      <div className="max-w-7xl mx-auto py-4 flex flex-col items-center justify-center min-h-[70vh]">
        <div>
          {/* Create account title */}
          <h1 className="text-4xl font-bold">Login</h1>
        </div>
        <Form {...form}>
          <form
            action=""
            className={cn("flex flex-col gap-4 w-full max-w-2xl mx-auto p-4")}
            onSubmit={form.handleSubmit(onSubmit)}
          >
            {/* Email/Username */}
            <FormField
              control={form.control}
              name="username_or_email"
              render={({ field }) => (
                <FormItem className={cn("w-full")}>
                  <FormLabel>Email/Username</FormLabel>
                  <FormControl>
                    <Input
                      placeholder="enter username or email"
                      className={cn("w-full")}
                      {...field}
                    />
                  </FormControl>
                  {/* <FormDescription>
                  This is your public display name.
                </FormDescription> */}
                  <FormMessage />
                </FormItem>
              )}
            />

            {/* Password */}
            <FormField
              control={form.control}
              name="password"
              render={({ field }) => (
                <FormItem>
                  <FormLabel>Password</FormLabel>
                  <FormControl>
                    <Input placeholder="********" type="password" {...field} />
                  </FormControl>
                  {/* <FormDescription>
                  This is your public display name.
                </FormDescription> */}
                  <FormMessage />
                </FormItem>
              )}
            />

            <Button
              type="submit"
              className={cn(
                "bg-primary text-white font-bold py-4 px-8 rounded-md",
                {
                  "opacity-50": mutation.isPending,
                  "cursor-not-allowed": mutation.isPending,
                }
              )}
              disabled={mutation.isPending}
            >
              {mutation.isPending ? "Loading..." : "login"}
            </Button>
            {/* Login link */}
            <div className="flex-1">
              <p>
                Don't have an account?{" "}
                <Link href="/auth/register" className="text-blue-500">
                  Create account
                </Link>
              </p>
            </div>
          </form>
        </Form>
      </div>
    </div>
  );
}

export default LoginPage;
